# --- Build stage ---
FROM golang:1.24-alpine AS builder

WORKDIR /src

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/client ./cmd/client

# --- Final stage ---
FROM alpine:3.19

WORKDIR /

COPY --from=builder /app/client /go-marketplace-client

# Для интерактивного режима
ENV TERM xterm-256color

ENTRYPOINT ["/go-marketplace-client"] 